MODEL:
  FEATURE_DIM: 18
  RESUME_EPOCH: 0
  NO_FEATURE_ONLY_RGB: False
  LOSS: "L1"
  USE_DEPTH: True
  USE_PC_NORM: False
  MUL_POINTNET: True
  UNET_LAYERS: [32, 64,180,450,450, 180,64,32,26]
  POINTNET_NPOINTS: [512, 80, 20, 8]
  POINTNET_RADIUS : [[0.02, 0.08], [0.08, 0.15], [0.15, 0.4], [0.4, 1.2]]
  NO_MODIFY: False 




INPUT:
  SIZE_TRAIN: [1024, 1024]
  SIZE_TEST: [1024, 1024]
  NEAR_FAR_SIZE: [[1.0, 8.5, 0.8]]
  USE_RGB: True
  RGB_MAP: False
  USE_DIR: "MAPS" 

DATASETS:
  TRAIN: [".data/vsense"]
  FRAME_NUM: [150]
  MASK: True
  SHIFT: 40
  MAXRATION: -0.5
  ROTATION: 10.0
  SUBJECT: 'redandblack'
  SKIP_STEP : [1] 
  IGNORE_FRAMES: [[]]
  MOVE_CAM: 0
  CROP: False


SOLVER:
  OPTIMIZER_NAME: "Adam"
  BASE_LR: 0.00001
  WEIGHT_DECAY: 0.000003
  IMS_PER_BATCH: 2
  WARMUP_FACTOR: 0.333
  WARMUP_ITERS: 3
  WARMUP_METHOD: "linear"
  MAX_EPOCHS: 100
  CHECKPOINT_PERIOD: 1

  START_ITERS: 5
  END_ITERS: 20
  LR_SCALE: 0.2

  LOSS_WHOLE_IMAGE: False



OUTPUT_DIR: "./logs/redandblack"
